services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: ./api
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      ASPNETCORE_URLS: http://+:5200
    depends_on:
      - mongo
    ports:
      - "5200:5200"
  web:
    build: ./web
    environment:
      VITE_API_URL: ${API_URL}
    ports:
      - "5173:4173"
    depends_on:
      - api
volumes:
  mongo_data:
